### ISSUE TITLE
Error: Attribute 'password' is longer than platform limit of 2560 chars

### ISSUE THREAD

**Issue by Koala811** [valentinegb/bonelab_mod_manager#1]
Can't connect my Account. Trying via email shows the error code Error: Attribute 'password' is longer than platform limit of 2560 chars
Also can not type something when trying to input the token.

**Comment by valentinegb** [comment]
What platform are you on? mod.io tokens are ***very*** long, and I only confirmed that I could store them using Apple Keychain. Also, you should be able to type when entering a token manually, but it intentionally does not show what you are typing (think of it like when you see •••••••• on websites).

**Comment by Koala811** [comment]
Oh, so does copy pasting the code via CTRL + V not do anything? I‘m on Windows 11.

**Comment by valentinegb** [comment]
Pasting in your token is expected, it would be insane to have someone type it in manually lol
There is a bug with a dependency, however, at least on macOS, that might freeze the program when you try to paste in your token.
I just about have a fix ready for the error it gave when you did the email login method, but I don't have a Windows computer. Would you be willing to download it and see if it fixes your issue?

**Comment by Koala811** [comment]
I dont know when I‘ll be back home, will test and respond back as soon as I‘m back home.

**Comment by Koala811** [comment]
I dont know when I‘ll be back home, will test and respond back as soon as I‘m back home.
Also, the program doesn‘t freeze or anything, it just won‘t let me Type anything. When pressing enter it always shows five or six ****** and shows the error code i mentioned. Dont know if this is maybe helpful. Will post a screenshot if the error is still there.

**Comment by valentinegb** [comment]
> Also, the program doesn‘t freeze or anything, it just won‘t let me Type anything. When pressing enter it always shows five or six ****** and shows the error code i mentioned. Dont know if this is maybe helpful. Will post a screenshot if the error is still there.

Oh, good! That probably means the warning message about the prompt only applies to Mac, which is okay because I'm probably going to be the only person involved in this that's on a Mac lol
If the fix (that I'm about to upload the build to) works, then the error should go away for both the email method and the token method. You should be able to paste your token (nothing will appear at first), press enter (the stars will appear), and then you should be logged in.

**Comment by valentinegb** [comment]
v0.1.1 has been pre-released, you can download it [here](https://github.com/valentinegb/bonelab_mod_manager/releases/tag/v0.1.1) when you're ready to try it.

**Comment by Ipmake** [comment]
Getting the same issue even with the v0.1.1 pre-release. I think the windows password vault has a password length limit

**Comment by valentinegb** [comment]
> Getting the same issue even with the v0.1.1 pre-release. I think the windows password vault has a password length limit

It does. In v0.1.1 I tried working around that by splitting the token into multiple entries, but that hasn't worked apparently... I might need to include some debug code in a build and see what it outputs.

**Comment by Ipmake** [comment]
Would it be an idea just to have an encrypted file sitting somewhere in the appdata directory that stores the token?

**Comment by valentinegb** [comment]
> Would it be an idea just to have an encrypted file sitting somewhere in the appdata directory that stores the token?

I used to actually just store the token in the `app_data` file, which is the file that the program creates and uses to keep track of installed mods and their versions and such, but I'm not really familiar with how I can encrypt that in a way that isn't easy to decrypt from a malicious program or person. That's why currently the program just relies on platform-specific password storing APIs.

**Comment by Ipmake** [comment]
I don't think encrypting it would be necessary, at least not for now. Don't think there's anyone targeting mod.io tokens and especially not when they're read only

**Comment by valentinegb** [comment]
Tokens created with the email code method *might* not be read only, I'm honestly not sure, I don't think there's a way to specify with the `modio` Rust library I'm using. I'm about to upload a new build and make a new release, but if I can't figure this out by the end of the day then yeah, I guess I'll just store it with the rest of the app data. Would prefer to not do that though, so I'll keep trying for now.

**Comment by valentinegb** [comment]
Sorry for the delay, [`v0.1.1-beta.1`](https://github.com/valentinegb/bonelab_mod_manager/releases/tag/v0.1.1-beta.1) is now up. This build has some debug code in it, so if you test it please let me know what it outputs!

**Comment by Ipmake** [comment]
Using the email method:
```
(Entered code and stuff)
[src/authentication.rs:53] remaining_password = "1613 characters long token starting with eyJlbm and ending with 09JsLVQ"
Error: Attribute 'password' is longer than platform limit of 2560 chars
Press q to quit
```

**Comment by valentinegb** [comment]
Whoops- sorry for accidentally asking you to tell me your token lol, meant to do `dbg!(remaining_password.len())` not `dbg!(remaining_password)`.
Anyway... yeah I've got pretty much no idea, it clearly isn't going over the limit but the error's still there. Might be time to give up and kindly ask that nobody goes snooping in the `app_data` file, or at least on Windows, I don't technically have to do the same on Mac and Linux where it works fine.

**Comment by valentinegb** [comment]
[`v0.1.1-beta.2`](https://github.com/valentinegb/bonelab_mod_manager/releases/tag/v0.1.1-beta.2) is ready, the Windows build shouldn't depend on `keyring` at all.

**Comment by Koala811** [comment]
Login with Token works now, got in first try.

**Comment by valentinegb** [comment]
Great, thank you everyone who participated for your assistance!
