### ISSUE TITLE
Invalid discriminant whilst choosing authentication method

### ISSUE THREAD

**Issue by tatatax** [valentinegb/bonelab_mod_manager#12]
when trying to log in via both mail and token, it gives an error: Found an Option discriminant that wasn't 0 or 1

**Comment by valentinegb** [comment]
What version are you using, and what platform?

**Comment by valentinegb** [comment]
I'm not able to reproduce the error you've described using v0.2.0 on Mac. Are you on Windows using the same version?

**Comment by tatatax** [comment]
I use windows I apologize for the long answer

**Comment by tatatax** [comment]
and yes I am using 0.2.0
and on version 0.1.1 there was no such thing

**Comment by valentinegb** [comment]
> I apologize for the long answer

No worries, thank you for the info! I'm getting a virtual machine setup right now so I can debug it on Windows.

**Comment by valentinegb** [comment]
It took a while, but I got a Windows virtual machine setup. I downloaded the Windows asset from the v0.2.0 release and ran it, but I didn't encounter any issues. Could you please make a screen recording showing the bug?

**Comment by tatatax** [comment]
![2023-09-06](https://github.com/valentinegb/bonelab_mod_manager/assets/144094605/54acfb2e-8152-44ea-b9d2-230373a03464)

**Comment by tatatax** [comment]
![image](https://github.com/valentinegb/bonelab_mod_manager/assets/144094605/46939e08-8395-4d96-b8de-fad7ea04f1fa)

**Comment by valentinegb** [comment]
Try setting the `RUST_BACKTRACE` environment variable to `1` and then run the program and send the result. If the syntax on Windows is like the syntax on unix based machines, then you can do that by running `RUST_BACKTRACE=1 ./bonelab_mod_manager.exe` in a terminal while in the directory containing the program. (You can use the `dir` command to navigate directories in a terminal on Windows, in case you aren't familiar, like `dir ./Downloads`.)

**Comment by tatatax** [comment]
I don't quite understand if you could record a video or something like that

**Comment by valentinegb** [comment]
https://github.com/valentinegb/bonelab_mod_manager/assets/35977727/d1d3f1f1-96a6-420a-9e48-04e56b30f8c4

I'm not sure how helpful this'll be since I'm on macOS, but the process should be similar. You should replace `cd` in the video with `dir`.

**Comment by tatatax** [comment]
dir Developer/bonelab_mod_manager/target/release/ writing this in windows powershell throws a dir error: Cannot find the path "C :\Users\KUVYLDA\Developer\bonelab _ mod _ manager\target\release\" because it does not exist.
line: 1 character: 1
+ dir Developer/bonelab_mod_manager/target/release/
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (C:\Users\КУВЫЛД...target\release\:String) [Get-ChildItem], ItemNotFoundException
+ FullyQualifiedErrorId: PathNotFound, Microsoft.PowerShell.Commands.GetChildItemCommand maybe I'm not writing it there?

**Comment by valentinegb** [comment]
The path I went to in the video is the path to my installation, but it isn't the same as yours. You need to go to the directory that contains *your* `bonelab_mod_manager.exe` file.

**Comment by tatatax** [comment]
I have this file in downloads

**Comment by valentinegb** [comment]
Then you would probably type something like `dir Downloads`

**Comment by tatatax** [comment]
i must write dir downloads/bonelab_mod_manager/target/release? but when i make the same mistake

**Comment by tatatax** [comment]
and then? I did it yesterday but I can't change anything there

**Comment by valentinegb** [comment]
Then try running `RUST_BACKTRACE=1 ./bonelab_mod_manager.exe` and use the program as you would to produce the error you reported

**Comment by tatatax** [comment]
PS C:\Users\КУВЫЛДА> RUST_BACKTRACE=1 ./bonelab_mod_manager.exe
RUST_BACKTRACE=1: The name "RUST_BACKTRACE=1" is not recognized as the name of the cmdlet, function, script file, or program being executed. Verify that the name is spelled correctly and that the path exists and is correct, and then try again.
line: 1 character: 1
+ RUST_BACKTRACE=1 ./bonelab_mod_manager.exe
+ ~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (RUST_BACKTRACE=1:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException

**Comment by valentinegb** [comment]
Okay, try `setx RUST_BACKTRACE "1"` and then `./bonelab_mod_manager.exe`

**Comment by tatatax** [comment]
gives it away

> PS C:\Users\КУВЫЛДА> RUST_BACKTRACE=1 ./bonelab_mod_manager.exe RUST_BACKTRACE=1: имя "RUST_BACKTRACE=1" не распознается как имя выполняемого командлета, функции, файла сценария или программы. Убедитесь, что имя написано правильно и что путь существует и является правильным, а затем повторите попытку. строка: 1 символ: 1
> 
> * RUST_BACKTRACE=1 ./bonelab_mod_manager.exe
> * 
> * Информация о категории: ObjectNotFound: (RUST_BACKTRACE=1:String) [], исключение CommandNotFoundException
> * Ошибка с полным правом : исключение CommandNotFoundException

**Comment by tatatax** [comment]
ok

**Comment by tatatax** [comment]
PS C :\Users\SOMERSAULT > setx RUST_BACKTRACE "1"

Success. The specified value is saved.

**Comment by tatatax** [comment]
and about the second the same

> PS C:\Users\КУВЫЛДА> RUST_BACKTRACE=1 ./bonelab_mod_manager.exe RUST_BACKTRACE=1: имя "RUST_BACKTRACE=1" не распознается как имя выполняемого командлета, функции, файла сценария или программы. Убедитесь, что имя написано правильно и что путь существует и является правильным, а затем повторите попытку. строка: 1 символ: 1
> 
> * RUST_BACKTRACE=1 ./bonelab_mod_manager.exe
> * 
> * Информация о категории: ObjectNotFound: (RUST_BACKTRACE=1:String) [], исключение CommandNotFoundException
> * Ошибка с полным правом : исключение CommandNotFoundException

**Comment by tatatax** [comment]
but the application has the same error

**Comment by valentinegb** [comment]
Don't run `RUST_BACKTRACE=1 ./bonelab_mod_manager.exe`, just `./bonelab_mod_manager.exe`

**Comment by tatatax** [comment]
just ./bonelab_mod_manager.exe after dir downloads just I can't do it

**Comment by valentinegb** [comment]
What's the output of `echo %RUST_BACKTRACE%`?

**Comment by tatatax** [comment]
PS C:\Users\КУВЫЛДА> echo %RUST_BACKTRACE%
%RUST_BACKTRACE%
PS C:\Users\КУВЫЛДА>

**Comment by valentinegb** [comment]
What about `echo $Env:RUST_BACKTRACE`?

**Comment by tatatax** [comment]
PS C:\Users\КУВЫЛДА> echo $Env:RUST_BACKTRACE
PS C:\Users\КУВЫЛДА>

**Comment by valentinegb** [comment]
Try `setx RUST_BACKTRACE "1" & echo $Env:RUST_BACKTRACE`

**Comment by tatatax** [comment]
PS C :\Users\SOMERSAULT > setx RUST_BACKTRACE "1"

Success. The specified value is saved.
PS C :\Users\SOMERSAULT > echo $ Env: RUST _ BACKTRACE

**Comment by valentinegb** [comment]
`setx RUST_BACKTRACE "1" & echo $Env:RUST_BACKTRACE` is meant to be executed exactly as it is on one line

**Comment by tatatax** [comment]
PS C:\Users\КУВЫЛДА> setx RUST_BACKTRACE "1" & echo $Env:RUST_BACKTRACE
строка:1 знак:25
+ setx RUST_BACKTRACE "1" & echo $Env:RUST_BACKTRACE
+                         ~
Амперсанд (&) не разрешен. Оператор & зарезервирован для будущих версий. Добавьте двойные кавычки до и после амперсанда ("&"), чтобы передать его как строку.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : AmpersandNotAllowed

**Comment by valentinegb** [comment]
Alright, at this point I'm giving up on trying to debug this lol, clearly I don't know enough about Windows to be able to
What you should try to do to fix this issue for yourself is navigate to `%AppData%` and delete the folder called `bonelab_mod_manager`, then the next time you run the program it will recreate the folder

**Comment by tatatax** [comment]
I will try

**Comment by tatatax** [comment]
should I close the problem?

**Comment by tatatax** [comment]
lol

**Comment by tatatax** [comment]
this was all that had to be done

**Comment by tatatax** [comment]
thank you

**Comment by valentinegb** [comment]
Don't worry about closing the issue, just let me know if you get it working or not and I'll handle it accordingly
Yeah- I'm sorry it took so long to get to this point, my goal was to find out what exactly was wrong so I could fix the code and prevent it from happening again, but oh well

**Comment by valentinegb** [comment]
Oh you already closed it lol, that's fine
