### ISSUE TITLE
Dependency `modio-rs` is missing field `monetisation_options`

### ISSUE THREAD

**Issue by OfficialZYNO** [valentinegb/bonelab_mod_manager#13]
After logging in and choosing "windows" as the platform of choice I get the following error:

✔ Which platform do you play Bonelab on? · Windows
Error: error decoding response body: missing field `monetisation_options` at line 1 column 3019: missing field `monetisation_options` at line 1 column 3019
Press q to quit

Any suggestions?

**Comment by valentinegb** [comment]
If you run the program again, does it ask you to select a platform again or does it immediately error?

**Comment by valentinegb** [comment]
> If you run the program again, does it ask you to select a platform again or does it immediately error?

Never mind actually, I can reproduce the error on my computer. My theory right now is that the mod.io API updated but the mod.io library that this project depends on has not yet, I'll contact the developer of that library.

**Comment by valentinegb** [comment]
Keep your eyes on [#8 of nickelc/modio-rs](https://github.com/nickelc/modio-rs/issues/8) for further updates.

**Comment by OfficialZYNO** [comment]
Thanks!

**Comment by valentinegb** [comment]
The underlying issue has been resolved! The project does need to be recompiled though. I will do that and release a new version once I can.

**Comment by valentinegb** [comment]
An update has been released.
