### ISSUE TITLE
issues getting it working

### ISSUE THREAD

**Issue by Nuclear-Python** [valentinegb/bonelab_mod_manager#17]
so im just having an issue getting it to actually install the mod i want it too, maybe i didnt to the initial set up first by not already having the mod downloaded onto my pc but when i open it to install a rexmeck weapon pack, it simply says that there are no mods to install. this is on a laptop tuning the latest version of windows 10

**Comment by valentinegb** [comment]
To get the mod manager to install and update a mod, you need to subscribe to it on https://mod.io. Have you done that?

**Comment by Nuclear-Python** [comment]
> To get the mod manager to install and update a mod, you need to subscribe to it on https://mod.io. Have you done that?

ah, thats where ive messed up, i thought i could download the zip file for the quest and the manager will for its magic from there. my bad and thank you for the quick response!

**Comment by valentinegb** [comment]
No problem! I've just now realized that I never actually mentioned that you need to subscribe to mods in the instructions! 😅 Just updated the `README.md` so people should know in the future
