### ISSUE TITLE
OS Error 267 Debug is not working/ the debug file is being removed whenever I attempt to use it 

### ISSUE THREAD

**Issue by beanie-3** [valentinegb/bonelab_mod_manager#28]
So I have gotten the os error 267 for the mod manager and I did check here if anyone else had any similar issues. Someone else did have a similar issue and a debug was put in place to fix it but whenever i would try and use the debug myself to hopefully fix the issue, the file would be deleted from my system. Im sure the reason for it is because of the anti-virus software i have installed but im not sure what to do to prevent it from removing the debug without having to uninstall the software itself. Some help would be much appreciated.

**Comment by beanie-3** [comment]
This issue did occur after I closed the manager accidentally while it was updating a mod and then reopening the manager, so that may play a role in what the issue.

**Comment by valentinegb** [comment]
The features added in that debug build have actually been merged into the latest release, they're just disabled by default. You can enable the logging by adding an environment variable named `RUST_LOG` and setting it to `debug` and another named `RUST_BACKTRACE` set to `1`. I don't have a Windows computer, assuming that's what you're using, but here's a guide for how to add environment variables on Windows: https://phoenixnap.com/kb/windows-set-environment-variable

**Comment by beanie-3** [comment]
I am using windows 11 and after doing what you instructed, this showed up on the mod manager 
![Screenshot 2023-11-21 213542](https://github.com/valentinegb/bonelab_mod_manager/assets/151701329/06744e88-d16a-4135-93a0-b692a053fd1a)
Im not sure if its because i messed up something or not

**Comment by valentinegb** [comment]
It looks like the problem originates from this mod: https://mod.io/g/bonelab/m/rexmecks-guns-in-game-accurate-replacer
It doesn't appear to be following the convention of distributing the mod in a folder for each platform, like the mod manager expects. Unfortunately, that means you can't use this mod with the mod manager. To remove it, find the files and folders that are part of it and remove them. The next time you run the mod manager, it should recognized that it's been removed and carry on. Let me know if this helps!

**Comment by valentinegb** [comment]
Oh and once everything's been resolved you can remove those two environment variables to return the mod manager to normal.

**Comment by beanie-3** [comment]
I had to uninstall all my mods due to not being able to find the rex gun replacer but the mod manager does work! Thank you for your help!

**Comment by valentinegb** [comment]
Sorry you had to remove your mods- but I'm glad the issue's been fixed and I'm glad I could help!
